services:
  hmscustomer:
    image: us-west1-docker.pkg.dev/hmscapstoneproject/hmsrepository2/hmscustomer
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hmscustomer-postgresql:5432/hmscustomer
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://hmscustomer-postgresql:5432/hmscustomer
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
  hmscustomer-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=hmscustomer
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  hmsdelivery:
    image: us-west1-docker.pkg.dev/hmscapstoneproject/hmsrepository2/hmsdelivery
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hmsdelivery-postgresql:5432/hmsdelivery
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://hmsdelivery-postgresql:5432/hmsdelivery
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
  hmsdelivery-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=hmsdelivery
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  hmsfinance:
    image: us-west1-docker.pkg.dev/hmscapstoneproject/hmsrepository2/hmsfinance
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hmsfinance-postgresql:5432/hmsfinance
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://hmsfinance-postgresql:5432/hmsfinance
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
  hmsfinance-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=hmsfinance
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  hmskitchen:
    image: us-west1-docker.pkg.dev/hmscapstoneproject/hmsrepository2/hmskitchen
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hmskitchen-postgresql:5432/hmskitchen
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://hmskitchen-postgresql:5432/hmskitchen
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
  hmskitchen-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=hmskitchen
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  hmsmenu:
    image: us-west1-docker.pkg.dev/hmscapstoneproject/hmsrepository2/hmsmenu
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hmsmenu-postgresql:5432/hmsmenu
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://hmsmenu-postgresql:5432/hmsmenu
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
  hmsmenu-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=hmsmenu
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  hmsnutritionist:
    image: us-west1-docker.pkg.dev/hmscapstoneproject/hmsrepository2/hmsnutritionist
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hmsnutritionist-postgresql:5432/hmsnutritionist
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://hmsnutritionist-postgresql:5432/hmsnutritionist
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
  hmsnutritionist-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=hmsnutritionist
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  hmscontact:
    image: us-west1-docker.pkg.dev/hmscapstoneproject/hmsrepository2/hmscontact
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hmscontact-postgresql:5432/hmscontact
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://hmscontact-postgresql:5432/hmscontact
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
  hmscontact-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=hmscontact
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  hmsgateway:
    image: us-west1-docker.pkg.dev/hmscapstoneproject/hmsrepository2/hmsgateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_R2DBC_URL=r2dbc:postgresql://hmsgateway-postgresql:5432/hmsgateway
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://hmsgateway-postgresql:5432/hmsgateway
      - JHIPSTER_SLEEP=60
      - JHIPSTER_REGISTRY_PASSWORD=admin
    ports:
      - "8087:8080"
  hmsgateway-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=hmsgateway
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  jhipster-registry:
    image: jhipster/jhipster-registry:v7.3.0
    volumes:
      - ./central-server-config:/central-config
    # By default the JHipster Registry runs with the "dev" and "native"
    # Spring profiles.
    # "native" profile means the filesystem is used to store data, see
    # http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_SECURITY_USER_PASSWORD=admin
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=git
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_URI=https://github.com/jhipster/jhipster-registry/
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_PATHS=central-config
    ports:
      - 8761:8761
